/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.0 at Fri Sep 26 22:21:43 2014. */

#include "client.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t NetMsgCmd_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, NetMsgCmd, Cmd, Cmd, 0),
    PB_LAST_FIELD
};


