/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.0 at Tue Sep 09 22:42:23 2014. */

#ifndef PB_CLIENT_PB_H_INCLUDED
#define PB_CLIENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _NetMsgCmd {
    uint32_t Cmd;
} NetMsgCmd;

/* Default values for struct fields */

/* Initializer values for message structs */
#define NetMsgCmd_init_default                   {0}
#define NetMsgCmd_init_zero                      {0}

/* Field tags (for use in manual encoding/decoding) */
#define NetMsgCmd_Cmd_tag                        1

/* Struct field encoding specification for nanopb */
extern const pb_field_t NetMsgCmd_fields[2];

/* Maximum encoded size of messages (where known) */
#define NetMsgCmd_size                           6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
