/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.0 at Wed Jun 03 00:59:23 2015. */

#include "client.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t NetMsgRequestPlayers_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t NetMsgCmd_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, NetMsgCmd, Cmd, Cmd, 0),
    PB_LAST_FIELD
};

const pb_field_t NetMsgNewPlayers_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, NetMsgNewPlayers, ClientId, ClientId, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, NetMsgNewPlayers, NumPlayers, ClientId, 0),
    PB_LAST_FIELD
};


