/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.0 at Wed Jun 17 22:24:01 2015. */

#ifndef PB_MSG_PB_H_INCLUDED
#define PB_MSG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _NRequestPlayers {
    uint8_t dummy_field;
} NRequestPlayers;

typedef struct _NActorDir {
    uint32_t UID;
    int32_t Dir;
} NActorDir;

typedef struct _NActorState {
    uint32_t UID;
    int32_t State;
} NActorState;

typedef struct _NAddPlayers {
    uint32_t ClientId;
    pb_size_t PlayerIds_count;
    uint32_t PlayerIds[4];
} NAddPlayers;

typedef struct _NCampaignDef {
    char Path[4096];
    int32_t GameMode;
    uint32_t Mission;
} NCampaignDef;

typedef struct _NClientId {
    uint32_t Id;
} NClientId;

typedef struct _NCmd {
    uint32_t Cmd;
} NCmd;

typedef struct _NNewPlayers {
    uint32_t ClientId;
    uint32_t NumPlayers;
} NNewPlayers;

typedef struct _NObjectiveCount {
    uint32_t ObjectiveId;
    uint32_t Count;
} NObjectiveCount;

typedef struct _NObjectiveUpdate {
    uint32_t ObjectiveId;
    int32_t Count;
} NObjectiveUpdate;

typedef struct _NPlayerData_CharLooks {
    int32_t Face;
    int32_t Skin;
    int32_t Arm;
    int32_t Body;
    int32_t Leg;
    int32_t Hair;
} NPlayerData_CharLooks;

typedef struct _NScore {
    uint32_t PlayerId;
    int32_t Score;
} NScore;

typedef struct _NVec2i {
    int32_t x;
    int32_t y;
} NVec2i;

typedef struct _NActorAdd {
    uint32_t UID;
    uint32_t CharId;
    int32_t Direction;
    int32_t Health;
    int32_t PlayerId;
    uint32_t TileItemFlags;
    NVec2i FullPos;
} NActorAdd;

typedef struct _NActorMove {
    uint32_t UID;
    NVec2i Pos;
} NActorMove;

typedef struct _NAddBullet {
    char BulletClass[128];
    NVec2i MuzzlePos;
    int32_t MuzzleHeight;
    float Angle;
    int32_t Elevation;
    uint32_t Flags;
    int32_t PlayerIndex;
    int32_t UID;
} NAddBullet;

typedef struct _NAddPickup {
    uint32_t UID;
    char PickupClass[128];
    bool IsRandomSpawned;
    int32_t SpawnerUID;
    uint32_t TileItemFlags;
    NVec2i Pos;
} NAddPickup;

typedef struct _NExploreTile {
    NVec2i Tile;
} NExploreTile;

typedef struct _NPlayerData {
    char Name[20];
    NPlayerData_CharLooks Looks;
    pb_size_t Weapons_count;
    char Weapons[3][128];
    uint32_t Lives;
    int32_t Score;
    int32_t TotalScore;
    int32_t Kills;
    int32_t Suicides;
    int32_t Friendlies;
    uint32_t PlayerIndex;
    bool IsUsed;
} NPlayerData;

/* Default values for struct fields */
extern const int32_t NActorAdd_PlayerId_default;
extern const int32_t NAddPickup_SpawnerUID_default;

/* Initializer values for message structs */
#define NRequestPlayers_init_default             {0}
#define NCmd_init_default                        {0}
#define NNewPlayers_init_default                 {0, 0}
#define NClientId_init_default                   {0}
#define NCampaignDef_init_default                {"", 0, 0}
#define NPlayerData_init_default                 {"", NPlayerData_CharLooks_init_default, 0, {"", "", ""}, 0, 0, 0, 0, 0, 0, 0, 0}
#define NPlayerData_CharLooks_init_default       {0, 0, 0, 0, 0, 0}
#define NObjectiveCount_init_default             {0, 0}
#define NAddPlayers_init_default                 {0, 0, {0, 0, 0, 0}}
#define NScore_init_default                      {0, 0}
#define NVec2i_init_default                      {0, 0}
#define NActorAdd_init_default                   {0, 0, 0, 0, -1, 0, NVec2i_init_default}
#define NActorMove_init_default                  {0, NVec2i_init_default}
#define NActorState_init_default                 {0, 0}
#define NActorDir_init_default                   {0, 0}
#define NAddPickup_init_default                  {0, "", 0, -1, 0, NVec2i_init_default}
#define NAddBullet_init_default                  {"", NVec2i_init_default, 0, 0, 0, 0, 0, 0}
#define NExploreTile_init_default                {NVec2i_init_default}
#define NObjectiveUpdate_init_default            {0, 0}
#define NRequestPlayers_init_zero                {0}
#define NCmd_init_zero                           {0}
#define NNewPlayers_init_zero                    {0, 0}
#define NClientId_init_zero                      {0}
#define NCampaignDef_init_zero                   {"", 0, 0}
#define NPlayerData_init_zero                    {"", NPlayerData_CharLooks_init_zero, 0, {"", "", ""}, 0, 0, 0, 0, 0, 0, 0, 0}
#define NPlayerData_CharLooks_init_zero          {0, 0, 0, 0, 0, 0}
#define NObjectiveCount_init_zero                {0, 0}
#define NAddPlayers_init_zero                    {0, 0, {0, 0, 0, 0}}
#define NScore_init_zero                         {0, 0}
#define NVec2i_init_zero                         {0, 0}
#define NActorAdd_init_zero                      {0, 0, 0, 0, 0, 0, NVec2i_init_zero}
#define NActorMove_init_zero                     {0, NVec2i_init_zero}
#define NActorState_init_zero                    {0, 0}
#define NActorDir_init_zero                      {0, 0}
#define NAddPickup_init_zero                     {0, "", 0, 0, 0, NVec2i_init_zero}
#define NAddBullet_init_zero                     {"", NVec2i_init_zero, 0, 0, 0, 0, 0, 0}
#define NExploreTile_init_zero                   {NVec2i_init_zero}
#define NObjectiveUpdate_init_zero               {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define NActorDir_UID_tag                        1
#define NActorDir_Dir_tag                        2
#define NActorState_UID_tag                      1
#define NActorState_State_tag                    2
#define NAddPlayers_ClientId_tag                 1
#define NAddPlayers_PlayerIds_tag                2
#define NCampaignDef_Path_tag                    1
#define NCampaignDef_GameMode_tag                2
#define NCampaignDef_Mission_tag                 3
#define NClientId_Id_tag                         1
#define NCmd_Cmd_tag                             1
#define NNewPlayers_ClientId_tag                 1
#define NNewPlayers_NumPlayers_tag               2
#define NObjectiveCount_ObjectiveId_tag          1
#define NObjectiveCount_Count_tag                2
#define NObjectiveUpdate_ObjectiveId_tag         1
#define NObjectiveUpdate_Count_tag               2
#define NPlayerData_CharLooks_Face_tag           1
#define NPlayerData_CharLooks_Skin_tag           2
#define NPlayerData_CharLooks_Arm_tag            3
#define NPlayerData_CharLooks_Body_tag           4
#define NPlayerData_CharLooks_Leg_tag            5
#define NPlayerData_CharLooks_Hair_tag           6
#define NScore_PlayerId_tag                      1
#define NScore_Score_tag                         2
#define NVec2i_x_tag                             1
#define NVec2i_y_tag                             2
#define NActorAdd_UID_tag                        1
#define NActorAdd_CharId_tag                     2
#define NActorAdd_Direction_tag                  3
#define NActorAdd_Health_tag                     4
#define NActorAdd_PlayerId_tag                   5
#define NActorAdd_TileItemFlags_tag              6
#define NActorAdd_FullPos_tag                    7
#define NActorMove_UID_tag                       1
#define NActorMove_Pos_tag                       2
#define NAddBullet_BulletClass_tag               1
#define NAddBullet_MuzzlePos_tag                 2
#define NAddBullet_MuzzleHeight_tag              3
#define NAddBullet_Angle_tag                     4
#define NAddBullet_Elevation_tag                 5
#define NAddBullet_Flags_tag                     6
#define NAddBullet_PlayerIndex_tag               7
#define NAddBullet_UID_tag                       8
#define NAddPickup_UID_tag                       1
#define NAddPickup_PickupClass_tag               2
#define NAddPickup_IsRandomSpawned_tag           3
#define NAddPickup_SpawnerUID_tag                4
#define NAddPickup_TileItemFlags_tag             5
#define NAddPickup_Pos_tag                       6
#define NExploreTile_Tile_tag                    1
#define NPlayerData_Name_tag                     1
#define NPlayerData_Looks_tag                    2
#define NPlayerData_Weapons_tag                  3
#define NPlayerData_Lives_tag                    4
#define NPlayerData_Score_tag                    5
#define NPlayerData_TotalScore_tag               6
#define NPlayerData_Kills_tag                    7
#define NPlayerData_Suicides_tag                 8
#define NPlayerData_Friendlies_tag               9
#define NPlayerData_PlayerIndex_tag              10
#define NPlayerData_IsUsed_tag                   11

/* Struct field encoding specification for nanopb */
extern const pb_field_t NRequestPlayers_fields[1];
extern const pb_field_t NCmd_fields[2];
extern const pb_field_t NNewPlayers_fields[3];
extern const pb_field_t NClientId_fields[2];
extern const pb_field_t NCampaignDef_fields[4];
extern const pb_field_t NPlayerData_fields[12];
extern const pb_field_t NPlayerData_CharLooks_fields[7];
extern const pb_field_t NObjectiveCount_fields[3];
extern const pb_field_t NAddPlayers_fields[3];
extern const pb_field_t NScore_fields[3];
extern const pb_field_t NVec2i_fields[3];
extern const pb_field_t NActorAdd_fields[8];
extern const pb_field_t NActorMove_fields[3];
extern const pb_field_t NActorState_fields[3];
extern const pb_field_t NActorDir_fields[3];
extern const pb_field_t NAddPickup_fields[7];
extern const pb_field_t NAddBullet_fields[9];
extern const pb_field_t NExploreTile_fields[2];
extern const pb_field_t NObjectiveUpdate_fields[3];

/* Maximum encoded size of messages (where known) */
#define NRequestPlayers_size                     0
#define NCmd_size                                6
#define NNewPlayers_size                         12
#define NClientId_size                           6
#define NCampaignDef_size                        4116
#define NPlayerData_size                         552
#define NPlayerData_CharLooks_size               66
#define NObjectiveCount_size                     12
#define NAddPlayers_size                         30
#define NScore_size                              17
#define NVec2i_size                              22
#define NActorAdd_size                           75
#define NActorMove_size                          30
#define NActorState_size                         17
#define NActorDir_size                           17
#define NAddPickup_size                          180
#define NAddBullet_size                          210
#define NExploreTile_size                        24
#define NObjectiveUpdate_size                    17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
