/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.0 at Tue Sep 30 22:19:24 2014. */

#include "server.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t NetMsgClientId_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, NetMsgClientId, Id, Id, 0),
    PB_LAST_FIELD
};

const pb_field_t NetMsgCampaignDef_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, NetMsgCampaignDef, Path, Path, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, NetMsgCampaignDef, CampaignMode, Path, 0),
    PB_LAST_FIELD
};

const pb_field_t NetMsgPlayerData_fields[10] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, NetMsgPlayerData, Name, Name, 0),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, NetMsgPlayerData, Looks, Name, &NetMsgPlayerData_CharLooks_fields),
    PB_FIELD(  3, STRING  , REPEATED, STATIC  , OTHER, NetMsgPlayerData, Weapons, Looks, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, NetMsgPlayerData, Score, Weapons, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, NetMsgPlayerData, TotalScore, Score, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, NetMsgPlayerData, Kills, TotalScore, 0),
    PB_FIELD(  7, INT32   , REQUIRED, STATIC  , OTHER, NetMsgPlayerData, Friendlies, Kills, 0),
    PB_FIELD(  8, INT32   , REQUIRED, STATIC  , OTHER, NetMsgPlayerData, PlayerIndex, Friendlies, 0),
    PB_FIELD(  9, BOOL    , REQUIRED, STATIC  , OTHER, NetMsgPlayerData, IsUsed, PlayerIndex, 0),
    PB_LAST_FIELD
};

const pb_field_t NetMsgPlayerData_CharLooks_fields[7] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, NetMsgPlayerData_CharLooks, Face, Face, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, NetMsgPlayerData_CharLooks, Skin, Face, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, NetMsgPlayerData_CharLooks, Arm, Skin, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, NetMsgPlayerData_CharLooks, Body, Arm, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, NetMsgPlayerData_CharLooks, Leg, Body, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, NetMsgPlayerData_CharLooks, Hair, Leg, 0),
    PB_LAST_FIELD
};

const pb_field_t NetMsgAddPlayers_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, NetMsgAddPlayers, ClientId, ClientId, 0),
    PB_FIELD(  2, INT32   , REPEATED, STATIC  , OTHER, NetMsgAddPlayers, PlayerIds, ClientId, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(NetMsgPlayerData, Looks) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_NetMsgClientId_NetMsgCampaignDef_NetMsgPlayerData_NetMsgPlayerData_CharLooks_NetMsgAddPlayers)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for NetMsgCampaignDef.Path is too large. Define PB_FIELD_16BIT to fix this.
#endif


