/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.0 at Sun Sep 07 20:47:54 2014. */

#ifndef PB_SERVER_PB_H_INCLUDED
#define PB_SERVER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _NetMsgCampaignDef {
    char Path[4096];
    uint32_t CampaignMode;
} NetMsgCampaignDef;

typedef struct _NetMsgPlayerId {
    uint32_t Id;
} NetMsgPlayerId;

/* Default values for struct fields */

/* Initializer values for message structs */
#define NetMsgCampaignDef_init_default           {"", 0}
#define NetMsgPlayerId_init_default              {0}
#define NetMsgCampaignDef_init_zero              {"", 0}
#define NetMsgPlayerId_init_zero                 {0}

/* Field tags (for use in manual encoding/decoding) */
#define NetMsgCampaignDef_Path_tag               1
#define NetMsgCampaignDef_CampaignMode_tag       2
#define NetMsgPlayerId_Id_tag                    1

/* Struct field encoding specification for nanopb */
extern const pb_field_t NetMsgCampaignDef_fields[3];
extern const pb_field_t NetMsgPlayerId_fields[2];

/* Maximum encoded size of messages (where known) */
#define NetMsgCampaignDef_size                   4105
#define NetMsgPlayerId_size                      6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
