/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.0 at Sun Sep 07 20:47:54 2014. */

#include "server.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t NetMsgCampaignDef_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, NetMsgCampaignDef, Path, Path, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, NetMsgCampaignDef, CampaignMode, Path, 0),
    PB_LAST_FIELD
};

const pb_field_t NetMsgPlayerId_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, NetMsgPlayerId, Id, Id, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for NetMsgCampaignDef.Path is too large. Define PB_FIELD_16BIT to fix this.
#endif


