/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.0 at Fri Sep 26 22:21:43 2014. */

#ifndef PB_SERVER_PB_H_INCLUDED
#define PB_SERVER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _NetMsgCampaignDef {
    char Path[4096];
    uint32_t CampaignMode;
} NetMsgCampaignDef;

typedef struct _NetMsgPlayerData_CharLooks {
    int32_t Face;
    int32_t Skin;
    int32_t Arm;
    int32_t Body;
    int32_t Leg;
    int32_t Hair;
} NetMsgPlayerData_CharLooks;

typedef struct _NetMsgPlayerData {
    char Name[20];
    NetMsgPlayerData_CharLooks Looks;
    pb_size_t Weapons_count;
    char Weapons[3][128];
    int32_t Score;
    int32_t TotalScore;
    int32_t Kills;
    int32_t Friendlies;
    int32_t PlayerIndex;
    int32_t TotalPlayers;
} NetMsgPlayerData;

/* Default values for struct fields */

/* Initializer values for message structs */
#define NetMsgCampaignDef_init_default           {"", 0}
#define NetMsgPlayerData_init_default            {"", NetMsgPlayerData_CharLooks_init_default, 0, {"", "", ""}, 0, 0, 0, 0, 0, 0}
#define NetMsgPlayerData_CharLooks_init_default  {0, 0, 0, 0, 0, 0}
#define NetMsgCampaignDef_init_zero              {"", 0}
#define NetMsgPlayerData_init_zero               {"", NetMsgPlayerData_CharLooks_init_zero, 0, {"", "", ""}, 0, 0, 0, 0, 0, 0}
#define NetMsgPlayerData_CharLooks_init_zero     {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define NetMsgCampaignDef_Path_tag               1
#define NetMsgCampaignDef_CampaignMode_tag       2
#define NetMsgPlayerData_CharLooks_Face_tag      1
#define NetMsgPlayerData_CharLooks_Skin_tag      2
#define NetMsgPlayerData_CharLooks_Arm_tag       3
#define NetMsgPlayerData_CharLooks_Body_tag      4
#define NetMsgPlayerData_CharLooks_Leg_tag       5
#define NetMsgPlayerData_CharLooks_Hair_tag      6
#define NetMsgPlayerData_Name_tag                1
#define NetMsgPlayerData_Looks_tag               2
#define NetMsgPlayerData_Weapons_tag             3
#define NetMsgPlayerData_Score_tag               4
#define NetMsgPlayerData_TotalScore_tag          5
#define NetMsgPlayerData_Kills_tag               6
#define NetMsgPlayerData_Friendlies_tag          7
#define NetMsgPlayerData_PlayerIndex_tag         8
#define NetMsgPlayerData_TotalPlayers_tag        9

/* Struct field encoding specification for nanopb */
extern const pb_field_t NetMsgCampaignDef_fields[3];
extern const pb_field_t NetMsgPlayerData_fields[10];
extern const pb_field_t NetMsgPlayerData_CharLooks_fields[7];

/* Maximum encoded size of messages (where known) */
#define NetMsgCampaignDef_size                   4105
#define NetMsgPlayerData_size                    549
#define NetMsgPlayerData_CharLooks_size          66

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
