/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "msg.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(NServerInfo, NServerInfo, AUTO)


PB_BIND(NClientId, NClientId, AUTO)


PB_BIND(NCampaignDef, NCampaignDef, 4)


PB_BIND(NColor, NColor, AUTO)


PB_BIND(NCharColors, NCharColors, AUTO)


PB_BIND(NPlayerStats, NPlayerStats, AUTO)


PB_BIND(NPlayerData, NPlayerData, 2)


PB_BIND(NPlayerRemove, NPlayerRemove, AUTO)


PB_BIND(NConfig, NConfig, 2)


PB_BIND(NTileSet, NTileSet, 2)


PB_BIND(NThingDamage, NThingDamage, AUTO)


PB_BIND(NMapObjectAdd, NMapObjectAdd, AUTO)


PB_BIND(NMapObjectRemove, NMapObjectRemove, AUTO)


PB_BIND(NScore, NScore, AUTO)


PB_BIND(NSound, NSound, AUTO)


PB_BIND(NVec2i, NVec2i, AUTO)


PB_BIND(NVec2, NVec2, AUTO)


PB_BIND(NGameBegin, NGameBegin, AUTO)


PB_BIND(NActorAdd, NActorAdd, 2)


PB_BIND(NActorMove, NActorMove, AUTO)


PB_BIND(NActorState, NActorState, AUTO)


PB_BIND(NActorDir, NActorDir, AUTO)


PB_BIND(NActorSlide, NActorSlide, AUTO)


PB_BIND(NActorImpulse, NActorImpulse, AUTO)


PB_BIND(NActorSwitchGun, NActorSwitchGun, AUTO)


PB_BIND(NActorPickupAll, NActorPickupAll, AUTO)


PB_BIND(NActorReplaceGun, NActorReplaceGun, AUTO)


PB_BIND(NActorHeal, NActorHeal, AUTO)


PB_BIND(NAmmo, NAmmo, AUTO)


PB_BIND(NActorAddAmmo, NActorAddAmmo, AUTO)


PB_BIND(NActorUseAmmo, NActorUseAmmo, AUTO)


PB_BIND(NActorDie, NActorDie, AUTO)


PB_BIND(NActorMelee, NActorMelee, AUTO)


PB_BIND(NActorPilot, NActorPilot, AUTO)


PB_BIND(NAddPickup, NAddPickup, AUTO)


PB_BIND(NRemovePickup, NRemovePickup, AUTO)


PB_BIND(NBulletBounce, NBulletBounce, AUTO)


PB_BIND(NRemoveBullet, NRemoveBullet, AUTO)


PB_BIND(NGunReload, NGunReload, AUTO)


PB_BIND(NGunFire, NGunFire, AUTO)


PB_BIND(NGunState, NGunState, AUTO)


PB_BIND(NAddBullet, NAddBullet, AUTO)


PB_BIND(NTrigger, NTrigger, AUTO)


PB_BIND(NExploreTiles, NExploreTiles, 2)


PB_BIND(NExploreTiles_Run, NExploreTiles_Run, AUTO)


PB_BIND(NRescueCharacter, NRescueCharacter, AUTO)


PB_BIND(NObjectiveUpdate, NObjectiveUpdate, AUTO)


PB_BIND(NAddKeys, NAddKeys, AUTO)


PB_BIND(NDoorToggle, NDoorToggle, AUTO)


PB_BIND(NMissionComplete, NMissionComplete, AUTO)


PB_BIND(NMissionEnd, NMissionEnd, AUTO)



